openapi: 3.1.0
info:
  title: Notion API
  version: 1.0.0
  description: API for retrieving pages in Notion.

servers:
  - url: https://api.notion.com/v1

paths:
  /pages/{page_id}:
    get:
      summary: Retrieve a page
      operationId: retrievePage
      parameters:
        - name: page_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: The ID of the page to retrieve.
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
            example: "2022-06-28"
      responses:
        '200':
          description: Successful retrieval of a page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponse'

components:
  schemas:
    PageResponse:
      type: object
      properties:
        object:
          type: string
          example: "page"
        id:
          type: string
          format: uuid
          description: The unique identifier of the page.
        created_time:
          type: string
          format: date-time
          description: The time when the page was created.
        last_edited_time:
          type: string
          format: date-time
          description: The time when the page was last edited.
        parent:
          type: object
          description: Information about the parent of the page.
        properties:
          type: object
          description: The properties of the page.
      required: [object, id, created_time, last_edited_time, parent, properties]
