openapi: 3.1.0
info:
  title: Notion API
  version: 1.0.0
  description: API for retrieving pages in Notion.
servers:
- url: https://api.notion.com/v1
paths:
  /pages/{page_id}:
    get:
      operationId: retrievePage
      parameters:
      - in: path
        name: page_id
        required: true
        schema:
          description: The ID of the page to retrieve.
          format: uuid
          type: string
      - in: header
        name: Notion-Version
        required: true
        schema:
          example: '2022-06-28'
          type: string
      - description: Filters the response to include only the specified page properties.
        in: query
        name: filter_properties
        required: false
        schema:
          description: A list of page property value IDs associated with the page.
            Use this param to limit the response to specific page property values.
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponse'
          description: Successful retrieval of a page
        '400':
          description: 'Bad Request: The request parameters are invalid.'
        '403':
          description: 'Forbidden: The integration does not have the required read
            content capabilities.'
        '404':
          description: 'Not Found: The page does not exist or the integration does
            not have access to the page.'
        '429':
          description: 'Too Many Requests: The request exceeds the API rate limits.'
      summary: Retrieve a page
components:
  schemas:
    PageResponse:
      properties:
        created_time:
          description: The time when the page was created.
          format: date-time
          type: string
        has_more:
          description: Indicates if there are more items beyond the current limit
            of 25 references.
          type: boolean
        id:
          description: The unique identifier of the page.
          format: uuid
          type: string
        last_edited_time:
          description: The time when the page was last edited.
          format: date-time
          type: string
        object:
          example: page
          type: string
        parent:
          description: Information about the parent of the page.
          type: object
        properties:
          description: The properties of the page.
          type: object
      required:
      - object
      - id
      - created_time
      - last_edited_time
      - parent
      - properties
      type: object
